name: Publish to Docker
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: jswanso
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jswanso/publish-to-GitHub-packages/game
          tag_with_sha: true
